
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisclusters/finalizers
  verbs:
  - update
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.containersolutions.com
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
