# permissions for end users to edit redisdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisdatabase-editor-role
rules:
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisdatabases/status
  verbs:
  - get
