# permissions for end users to view redisdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisdatabase-viewer-role
rules:
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisdatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.containersolutions.com
  resources:
  - redisdatabases/status
  verbs:
  - get
