
---
apiVersion: redis.containersolutions.com/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster-sample
  namespace: default
spec:
  replicas: 3
  # auth:
  #   secret: redis-auth
monitoringtemplate:
  containers:
  - name: nginx
    image: k8s.gcr.io/nginx-slim:0.8
    ports:
    - containerPort: 80
      name: monitor
  
