
---
apiVersion: redis.containersolutions.com/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster-sample
  namespace: default
spec:
  replicas: 3
  # auth:
  #   secret: redis-auth
  monitoringtemplate:
    metadata:
      labels:
        random: label
    spec:
      containers:
        - name: monitoring
          image: redis-redis-metrics
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: monitor
                  
---
kind: ConfigMap

metadata:
  name: rediscluster-sample-monitoring
  namespace: default

    
  
