apiVersion: redis.containersolutions.com/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster-sample
  namespace: default
  labels:
    app: redis-graph
    team: team-a
spec:
  replicas: 1
  storage: 3Gi
  image: redislabs/redisgraph:2.4.1
  config: |
    maxmemory 2600mb
    maxmemory-samples 5
    maxmemory-policy allkeys-lru
    appendonly yes
    protected-mode no
    loadmodule /usr/lib/redis/modules/redisgraph.so
  # auth:
  #   secret: redis-auth
  # monitoring:
  #   spec:
  #     volumes:
  #       - name: rediscluster-samplemonitoring-config
  #     containers:
  #       - name: monitoring
  #         image: redis-redis-metrics
  #         # env:
  #         #   - name: REDISAUTH
  #         #     valueFrom:
  #         #       secretKeyRef:
  #         #         name: redis-auth
  #         #         key: requirepass
  #         ports:
  #           - containerPort: 8080
  #             name: monitor
                  
---
