namespace: default

resources:
- operator.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - redis_operator_config.yaml
  name: redis-operator-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/containersolutions/redis-operator
  newName: ghcr.io/containersolutions/redis-operator
  newTag: latest
