resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

namespace: devops-redis-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/containersolutions/redis-operator
  newName: ghcr.io/containersolutions/redis-operator
  newTag: 0.2.7
